/* NESTED If..else statements are the ones in whichone conditional statement (isf statement or if.. else statement) 
is nested inside another conditional statement ( if statement ot if else statement) */


/*
if (condition1){
    if(condition2){
        //condition to executed if the both conditipn1 and condition 2 are true
    
    }

}
    */




let age = 17
let haslincense = false

if(age > 18){
    if(haslincense){
        console.log("you can drive the vechile")
    }
    else{
        console.log("you must get the driving license"

        )
    }

}
else(
    console.log("youa are too young to drive the vechile")
)